# Generated by Django 6.0.5 on 2026-05-29 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Namangan', 'Namangan'), ('Andijan', 'Andijan'), ('Fergana', 'Fergana'), ('Nukus', 'Nukus'), ('Karshi', 'Karshi'), ('Termez', 'Termez'), ('Jizzakh', 'Jizzakh'), ('Gulistan', 'Gulistan'), ('Navoi', 'Navoi'), ('Urgench', 'Urgench'), ('Other', 'Other')], default='Tashkent', max_length=50)),
                ('uni_type', models.CharField(choices=[('state', 'State'), ('private', 'Private'), ('international', 'International')], default='state', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('application_link', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('quota_2024', models.PositiveIntegerField(default=0)),
                ('quota_2025', models.PositiveIntegerField(default=0)),
                ('min_score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('tuition_usd', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True)),
                ('duration_years', models.PositiveSmallIntegerField(default=4)),
                ('language', models.CharField(default='Uzbek/Russian', max_length=100)),
                ('degree_type', models.CharField(default='Bachelor', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='universities.university')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='universities.university')),
            ],
            options={
                'unique_together': {('user', 'university')},
            },
        ),
    ]
